### ISSUE TITLE
Difficulty bomb

### ISSUE THREAD

**Issue by immartian** [Musicoin/MCIPs#2]
Difficulty bomb is a legacy issue planted in Ethereum blockchain to set a harsh deadline for the project team to switch to POS(proof-of-stake). Yet PoS is still not mature, the difficult bomb is closer to explode for both ETH and ETC(ETC, nevertheless, managed to delay the process with one hard fork). 

We need to have a solution to face the deadline as well since it will come inexorably. One idea is to delay it to a longer time(ie. 3 more years) with a hard fork to give enough timespace to think about future solutions; another idea is to leave it along and just boost our investment on development  on Proof-of-sharing (different from Proof-of-stake). Either way, we need some concrete roadmap before too long, it's why I create this issue to discuss and all comments are welcome.

**Comment by thepeekay** [comment]
One thing to be considered is how realistic is to have a Proof-of-sharing solution in place, before the difficulty bomb becomes an issue. 

Giving some head room with a hard fork can both benefit but also harm in long term. Benefit as it gives more time to design and implement the solution in a better way, but can also harm as not having a concrete date as a deadline, might not put enough pressure on the implementation, which is one of the reasons the bomb was put in place, both pressure in the community to finish up PoS work but also force miners to switch from PoW.

**Comment by trustfarm-dev** [comment]
@immartian I agree @pkefal 's opinion.
first delaying the TimeBomb, similar with ETC.
Also, DAG Size less increase slopes is another options.

And, independently go on Proof Of Sharing is better I think.

**Comment by immartian** [comment]
It's good idea, we can ease the bomb a bit before PoS get fully realized and validated.
