### ISSUE TITLE
Geo information to musician's profile

### ISSUE THREAD

**Issue by immartian** [Musicoin/MCIPs#4]
We should consider better collection and presentation of geographical information to a musician since it's a global project with many language diversity. Let's find a better design in "Application" layer.

**Comment by Dano-Sato** [comment]
I think listening a music doesn't require any geographical information in itself. As I know there is no wall in global music world. The existing platform in itself doesn't require a lot of ability in English. Other than that, As an enhancement of application layer, I want Musicoin wallet as a music player, which recommends favorable music for listener. I think Musicoin needs a useful smartphone application to make a global adaptation of itself. Of course it could be too fanciful for developer's view(cuz I'm not good at programming, I'm a student) But that would make listeners get friendly with Musicoin,(there is a lot of listeners doesn't even know how to make a Musicoin wallet) I would be glad to hear your reply to this proposal.

**Comment by immartian** [comment]
Ya, it's on our roadmap, $MUSIC on desktop.

**Comment by etaletai13** [comment]
I do think that this will be a nice feature, especially if you would like to hear from artists nearby. I agree that we need to remain and strive for friendliness to the listener and the publisher; but also we need to lower the barrier to contributing in code, as much as possible. Priorities, rightly, go Listener; Publisher; Coder; Company. Any other, the bit will fail.

**Comment by immartian** [comment]
will get it considered in middleware level instead of on-chain.
